// <auto-generated />
using System;
using Analysis.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Analysis.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ResearchDbContext))]
    [Migration("20260905210022_M2CatalogObservations")]
    partial class M2CatalogObservations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("research")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Analysis.Domain.Asset", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.ToTable("Assets", "research");

                    b.HasData(
                        new
                        {
                            Id = "bitcoin",
                            Name = "Bitcoin",
                            Symbol = "BTC"
                        },
                        new
                        {
                            Id = "ethereum",
                            Name = "Ether",
                            Symbol = "ETH"
                        },
                        new
                        {
                            Id = "solana",
                            Name = "Solana",
                            Symbol = "SOL"
                        });
                });

            modelBuilder.Entity("Analysis.Domain.InstrumentRef", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasColumnType("character varying(32)");

                    b.Property<string>("BaseUnit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("NativeSymbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("character varying(32)");

                    b.Property<string>("QuoteUnit")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("SettlementUnit")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("ProviderId", "Kind", "NativeSymbol")
                        .IsUnique();

                    b.ToTable("ProviderInstrumentRefs", "research");

                    b.HasData(
                        new
                        {
                            Id = "binance:spot:BTCUSDT",
                            AssetId = "bitcoin",
                            BaseUnit = "BTC",
                            Kind = "Spot",
                            NativeSymbol = "BTCUSDT",
                            ProviderId = "binance",
                            QuoteUnit = "USDT"
                        },
                        new
                        {
                            Id = "bybit:linear:BTCUSDT",
                            AssetId = "bitcoin",
                            BaseUnit = "BTC",
                            Kind = "LinearPerpetual",
                            NativeSymbol = "BTCUSDT",
                            ProviderId = "bybit",
                            QuoteUnit = "USDT",
                            SettlementUnit = "USDT"
                        },
                        new
                        {
                            Id = "binance:spot:ETHUSDT",
                            AssetId = "ethereum",
                            BaseUnit = "ETH",
                            Kind = "Spot",
                            NativeSymbol = "ETHUSDT",
                            ProviderId = "binance",
                            QuoteUnit = "USDT"
                        },
                        new
                        {
                            Id = "bybit:linear:ETHUSDT",
                            AssetId = "ethereum",
                            BaseUnit = "ETH",
                            Kind = "LinearPerpetual",
                            NativeSymbol = "ETHUSDT",
                            ProviderId = "bybit",
                            QuoteUnit = "USDT",
                            SettlementUnit = "USDT"
                        },
                        new
                        {
                            Id = "binance:spot:SOLUSDT",
                            AssetId = "solana",
                            BaseUnit = "SOL",
                            Kind = "Spot",
                            NativeSymbol = "SOLUSDT",
                            ProviderId = "binance",
                            QuoteUnit = "USDT"
                        },
                        new
                        {
                            Id = "bybit:linear:SOLUSDT",
                            AssetId = "solana",
                            BaseUnit = "SOL",
                            Kind = "LinearPerpetual",
                            NativeSymbol = "SOLUSDT",
                            ProviderId = "bybit",
                            QuoteUnit = "USDT",
                            SettlementUnit = "USDT"
                        },
                        new
                        {
                            Id = "defillama:chain:Ethereum",
                            AssetId = "ethereum",
                            BaseUnit = "ETH",
                            Kind = "Chain",
                            NativeSymbol = "Ethereum",
                            ProviderId = "defillama"
                        },
                        new
                        {
                            Id = "defillama:chain:Solana",
                            AssetId = "solana",
                            BaseUnit = "SOL",
                            Kind = "Chain",
                            NativeSymbol = "Solana",
                            ProviderId = "defillama"
                        });
                });

            modelBuilder.Entity("Analysis.Infrastructure.Persistence.ObservationRow", b =>
                {
                    b.Property<string>("InstrumentId")
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Kind")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("EventTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PeriodSeconds")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Close")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("High")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("IngestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Low")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Open")
                        .HasColumnType("numeric");

                    b.Property<string>("PayloadId")
                        .IsRequired()
                        .HasColumnType("character varying(64)");

                    b.Property<string>("QuoteUnit")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<decimal?>("QuoteVolume")
                        .HasColumnType("numeric");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<decimal?>("Value")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Volume")
                        .HasColumnType("numeric");

                    b.HasKey("InstrumentId", "Kind", "EventTimeUtc", "PeriodSeconds");

                    b.HasIndex("PayloadId", "InstrumentId");

                    b.ToTable("Observations", "research", t =>
                        {
                            t.HasCheckConstraint("CK_Observation_kind", "\"Kind\" IN ('Candle', 'FundingRate', 'OpenInterestBothSides', 'ChainTvl')");

                            t.HasCheckConstraint("CK_Observation_period", "\"PeriodSeconds\" >= 0");

                            t.HasCheckConstraint("CK_Observation_scalar", "\"Kind\" = 'Candle' OR (\"Kind\" = 'FundingRate' AND \"Unit\" = 'fraction' AND \"Value\" BETWEEN -1 AND 1 AND \"PeriodSeconds\" = 0) OR (\"Kind\" = 'OpenInterestBothSides' AND \"Value\" >= 0 AND \"PeriodSeconds\" = 3600) OR (\"Kind\" = 'ChainTvl' AND \"Unit\" = 'USD' AND \"Value\" >= 0 AND \"PeriodSeconds\" = 0)");

                            t.HasCheckConstraint("CK_Observation_shape", "(\"Kind\" = 'Candle' AND \"Open\" IS NOT NULL AND \"High\" IS NOT NULL AND \"Low\" IS NOT NULL AND \"Close\" IS NOT NULL AND \"Volume\" IS NOT NULL AND \"QuoteVolume\" IS NOT NULL AND \"QuoteUnit\" IS NOT NULL AND \"Open\" > 0 AND \"Low\" > 0 AND \"Open\" BETWEEN \"Low\" AND \"High\" AND \"Close\" BETWEEN \"Low\" AND \"High\" AND \"Volume\" >= 0 AND \"QuoteVolume\" >= 0 AND \"Value\" IS NULL AND \"PeriodSeconds\" = 3600) OR (\"Kind\" <> 'Candle' AND \"Value\" IS NOT NULL AND \"Open\" IS NULL AND \"High\" IS NULL AND \"Low\" IS NULL AND \"Close\" IS NULL AND \"Volume\" IS NULL AND \"QuoteVolume\" IS NULL AND \"QuoteUnit\" IS NULL)");
                        });
                });

            modelBuilder.Entity("Analysis.Infrastructure.Persistence.PayloadRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("IngestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InstrumentId")
                        .IsRequired()
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MappingVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RequestPath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("WindowEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("WindowStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.ToTable("ProviderPayloads", "research");
                });

            modelBuilder.Entity("Analysis.Infrastructure.Persistence.ProviderRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.ToTable("Providers", "research");

                    b.HasData(
                        new
                        {
                            Id = "binance",
                            ApprovalStatus = "Unresolved"
                        },
                        new
                        {
                            Id = "bybit",
                            ApprovalStatus = "Unresolved"
                        },
                        new
                        {
                            Id = "defillama",
                            ApprovalStatus = "Unresolved"
                        });
                });

            modelBuilder.Entity("Analysis.Infrastructure.Persistence.QuarantineRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("IngestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InstrumentId")
                        .IsRequired()
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("WindowEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("WindowStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.ToTable("Quarantine", "research");
                });

            modelBuilder.Entity("Analysis.Domain.InstrumentRef", b =>
                {
                    b.HasOne("Analysis.Domain.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Analysis.Infrastructure.Persistence.ProviderRow", null)
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Analysis.Infrastructure.Persistence.ObservationRow", b =>
                {
                    b.HasOne("Analysis.Domain.InstrumentRef", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Analysis.Infrastructure.Persistence.PayloadRow", null)
                        .WithMany()
                        .HasForeignKey("PayloadId", "InstrumentId")
                        .HasPrincipalKey("Id", "InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Analysis.Infrastructure.Persistence.PayloadRow", b =>
                {
                    b.HasOne("Analysis.Domain.InstrumentRef", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Analysis.Infrastructure.Persistence.QuarantineRow", b =>
                {
                    b.HasOne("Analysis.Domain.InstrumentRef", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
