// <auto-generated />
using System;
using Analysis.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Analysis.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ResearchDbContext))]
    partial class ResearchDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("research")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Analysis.Domain.Asset", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.ToTable("Assets", "research");

                    b.HasData(
                        new
                        {
                            Id = "bitcoin",
                            Name = "Bitcoin",
                            Symbol = "BTC"
                        },
                        new
                        {
                            Id = "ethereum",
                            Name = "Ether",
                            Symbol = "ETH"
                        },
                        new
                        {
                            Id = "solana",
                            Name = "Solana",
                            Symbol = "SOL"
                        });
                });

            modelBuilder.Entity("Analysis.Domain.InstrumentRef", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasColumnType("character varying(32)");

                    b.Property<string>("BaseUnit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("NativeSymbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("character varying(32)");

                    b.Property<string>("QuoteUnit")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("SettlementUnit")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("ProviderId", "Kind", "NativeSymbol")
                        .IsUnique();

                    b.ToTable("ProviderInstrumentRefs", "research");

                    b.HasData(
                        new
                        {
                            Id = "binance:spot:BTCUSDT",
                            AssetId = "bitcoin",
                            BaseUnit = "BTC",
                            Kind = "Spot",
                            NativeSymbol = "BTCUSDT",
                            ProviderId = "binance",
                            QuoteUnit = "USDT"
                        },
                        new
                        {
                            Id = "bybit:linear:BTCUSDT",
                            AssetId = "bitcoin",
                            BaseUnit = "BTC",
                            Kind = "LinearPerpetual",
                            NativeSymbol = "BTCUSDT",
                            ProviderId = "bybit",
                            QuoteUnit = "USDT",
                            SettlementUnit = "USDT"
                        },
                        new
                        {
                            Id = "binance:spot:ETHUSDT",
                            AssetId = "ethereum",
                            BaseUnit = "ETH",
                            Kind = "Spot",
                            NativeSymbol = "ETHUSDT",
                            ProviderId = "binance",
                            QuoteUnit = "USDT"
                        },
                        new
                        {
                            Id = "bybit:linear:ETHUSDT",
                            AssetId = "ethereum",
                            BaseUnit = "ETH",
                            Kind = "LinearPerpetual",
                            NativeSymbol = "ETHUSDT",
                            ProviderId = "bybit",
                            QuoteUnit = "USDT",
                            SettlementUnit = "USDT"
                        },
                        new
                        {
                            Id = "binance:spot:SOLUSDT",
                            AssetId = "solana",
                            BaseUnit = "SOL",
                            Kind = "Spot",
                            NativeSymbol = "SOLUSDT",
                            ProviderId = "binance",
                            QuoteUnit = "USDT"
                        },
                        new
                        {
                            Id = "bybit:linear:SOLUSDT",
                            AssetId = "solana",
                            BaseUnit = "SOL",
                            Kind = "LinearPerpetual",
                            NativeSymbol = "SOLUSDT",
                            ProviderId = "bybit",
                            QuoteUnit = "USDT",
                            SettlementUnit = "USDT"
                        },
                        new
                        {
                            Id = "defillama:chain:Ethereum",
                            AssetId = "ethereum",
                            BaseUnit = "ETH",
                            Kind = "Chain",
                            NativeSymbol = "Ethereum",
                            ProviderId = "defillama"
                        },
                        new
                        {
                            Id = "defillama:chain:Solana",
                            AssetId = "solana",
                            BaseUnit = "SOL",
                            Kind = "Chain",
                            NativeSymbol = "Solana",
                            ProviderId = "defillama"
                        });
                });

            modelBuilder.Entity("Analysis.Infrastructure.Persistence.CategoryScoreRow", b =>
                {
                    b.Property<string>("ScoreId")
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<int>("ApplicableWeight")
                        .HasColumnType("integer");

                    b.Property<int>("AvailableWeight")
                        .HasColumnType("integer");

                    b.Property<string>("BatchId")
                        .IsRequired()
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("DataQuality")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Score")
                        .HasColumnType("numeric");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ScoreId", "Category");

                    b.HasIndex("ScoreId", "BatchId");

                    b.ToTable("CategoryScores", "research", t =>
                        {
                            t.HasCheckConstraint("CK_M3_category", "\"Category\" IN ('price','derivatives','fundamentals','regime') AND \"State\" IN ('complete','partial','missing','inapplicable') AND \"DataQuality\" BETWEEN 0 AND 100 AND (\"Score\" IS NULL OR \"Score\" BETWEEN -100 AND 100) AND \"AvailableWeight\" BETWEEN 0 AND \"ApplicableWeight\"");

                            t.HasCheckConstraint("CK_M3_category_state", "(\"State\" IN ('complete','partial') AND \"Score\" IS NOT NULL) OR (\"State\" IN ('missing','inapplicable') AND \"Score\" IS NULL)");
                        });
                });

            modelBuilder.Entity("Analysis.Infrastructure.Persistence.FeatureSnapshotRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("AsOfUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasColumnType("character varying(32)");

                    b.Property<string>("BatchId")
                        .IsRequired()
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("CorePriceReady")
                        .HasColumnType("boolean");

                    b.Property<string>("FeatureHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId", "AsOfUtc", "ModelId")
                        .IsUnique();

                    b.HasIndex("BatchId", "AsOfUtc", "ModelId");

                    b.ToTable("FeatureSnapshots", "research");
                });

            modelBuilder.Entity("Analysis.Infrastructure.Persistence.FeatureValueRow", b =>
                {
                    b.Property<string>("SnapshotId")
                        .HasColumnType("character varying(64)");

                    b.Property<int>("FeatureId")
                        .HasColumnType("integer");

                    b.Property<string>("BatchId")
                        .IsRequired()
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CalculationVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DetailJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("SnapshotId", "FeatureId");

                    b.HasIndex("SnapshotId", "BatchId");

                    b.ToTable("FeatureValues", "research", t =>
                        {
                            t.HasCheckConstraint("CK_M3_feature_id", "\"FeatureId\" BETWEEN 1 AND 21");

                            t.HasCheckConstraint("CK_M3_feature_numeric", "\"Value\" IS NULL OR (\"Value\" NOT IN ('NaN'::numeric,'Infinity'::numeric,'-Infinity'::numeric) AND scale(\"Value\") <= 18 AND abs(\"Value\") < 1e28)");

                            t.HasCheckConstraint("CK_M3_feature_state", "(\"State\" = 'available' AND \"Value\" IS NOT NULL) OR (\"State\" IN ('missing','stale','invalid','conflicted','inapplicable') AND \"Value\" IS NULL)");
                        });
                });

            modelBuilder.Entity("Analysis.Infrastructure.Persistence.InputConflictRow", b =>
                {
                    b.Property<string>("BatchId")
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ConflictId")
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FactJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BatchId", "ConflictId");

                    b.HasIndex("ConflictId");

                    b.ToTable("InputConflicts", "research");
                });

            modelBuilder.Entity("Analysis.Infrastructure.Persistence.InputObservationRow", b =>
                {
                    b.Property<string>("BatchId")
                        .HasColumnType("character varying(64)");

                    b.Property<string>("InstrumentId")
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Kind")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("EventTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PeriodSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("FactJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BatchId", "InstrumentId", "Kind", "EventTimeUtc", "PeriodSeconds");

                    b.HasIndex("InstrumentId", "Kind", "EventTimeUtc", "PeriodSeconds");

                    b.ToTable("InputObservations", "research");
                });

            modelBuilder.Entity("Analysis.Infrastructure.Persistence.ObservationRow", b =>
                {
                    b.Property<string>("InstrumentId")
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Kind")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("EventTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PeriodSeconds")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Close")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("High")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("IngestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Low")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Open")
                        .HasColumnType("numeric");

                    b.Property<string>("PayloadId")
                        .IsRequired()
                        .HasColumnType("character varying(64)");

                    b.Property<string>("QuoteUnit")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<decimal?>("QuoteVolume")
                        .HasColumnType("numeric");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<decimal?>("Value")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Volume")
                        .HasColumnType("numeric");

                    b.HasKey("InstrumentId", "Kind", "EventTimeUtc", "PeriodSeconds");

                    b.HasIndex("PayloadId", "InstrumentId");

                    b.ToTable("Observations", "research", t =>
                        {
                            t.HasCheckConstraint("CK_Observation_kind", "\"Kind\" IN ('Candle', 'FundingRate', 'OpenInterestBothSides', 'ChainTvl')");

                            t.HasCheckConstraint("CK_Observation_period", "\"PeriodSeconds\" >= 0");

                            t.HasCheckConstraint("CK_Observation_scalar", "\"Kind\" = 'Candle' OR (\"Kind\" = 'FundingRate' AND \"Unit\" = 'fraction' AND \"Value\" BETWEEN -1 AND 1 AND \"PeriodSeconds\" = 0) OR (\"Kind\" = 'OpenInterestBothSides' AND \"Value\" >= 0 AND \"PeriodSeconds\" = 3600) OR (\"Kind\" = 'ChainTvl' AND \"Unit\" = 'USD' AND \"Value\" >= 0 AND \"PeriodSeconds\" = 0)");

                            t.HasCheckConstraint("CK_Observation_shape", "(\"Kind\" = 'Candle' AND \"Open\" IS NOT NULL AND \"High\" IS NOT NULL AND \"Low\" IS NOT NULL AND \"Close\" IS NOT NULL AND \"Volume\" IS NOT NULL AND \"QuoteVolume\" IS NOT NULL AND \"QuoteUnit\" IS NOT NULL AND \"Open\" > 0 AND \"Low\" > 0 AND \"Open\" BETWEEN \"Low\" AND \"High\" AND \"Close\" BETWEEN \"Low\" AND \"High\" AND \"Volume\" >= 0 AND \"QuoteVolume\" >= 0 AND \"Value\" IS NULL AND \"PeriodSeconds\" = 3600) OR (\"Kind\" <> 'Candle' AND \"Value\" IS NOT NULL AND \"Open\" IS NULL AND \"High\" IS NULL AND \"Low\" IS NULL AND \"Close\" IS NULL AND \"Volume\" IS NULL AND \"QuoteVolume\" IS NULL AND \"QuoteUnit\" IS NULL)");
                        });
                });

            modelBuilder.Entity("Analysis.Infrastructure.Persistence.PayloadRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("IngestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InstrumentId")
                        .IsRequired()
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MappingVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RequestPath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("WindowEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("WindowStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.ToTable("ProviderPayloads", "research");
                });

            modelBuilder.Entity("Analysis.Infrastructure.Persistence.ProviderRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.ToTable("Providers", "research");

                    b.HasData(
                        new
                        {
                            Id = "binance",
                            ApprovalStatus = "Unresolved"
                        },
                        new
                        {
                            Id = "bybit",
                            ApprovalStatus = "Unresolved"
                        },
                        new
                        {
                            Id = "defillama",
                            ApprovalStatus = "Unresolved"
                        });
                });

            modelBuilder.Entity("Analysis.Infrastructure.Persistence.QuarantineRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("IngestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InstrumentId")
                        .IsRequired()
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("WindowEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("WindowStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.ToTable("Quarantine", "research");
                });

            modelBuilder.Entity("Analysis.Infrastructure.Persistence.ScoreSnapshotRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("AsOfUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AssetId")
                        .IsRequired()
                        .HasColumnType("character varying(32)");

                    b.Property<string>("BatchId")
                        .IsRequired()
                        .HasColumnType("character varying(64)");

                    b.Property<decimal?>("BearishConfidence")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BullishConfidence")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Composite")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ContextCoverage")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DataQuality")
                        .HasColumnType("numeric");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ScoreHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScoreJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SnapshotId")
                        .IsRequired()
                        .HasColumnType("character varying(64)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssetId", "AsOfUtc", "ModelId")
                        .IsUnique();

                    b.HasIndex("ModelId", "AsOfUtc", "AssetId");

                    b.HasIndex("SnapshotId", "BatchId", "AssetId", "AsOfUtc", "ModelId")
                        .IsUnique();

                    b.ToTable("ScoreSnapshots", "research", t =>
                        {
                            t.HasCheckConstraint("CK_M3_score_bounds", "(\"Composite\" IS NULL OR \"Composite\" BETWEEN -100 AND 100) AND (\"BullishConfidence\" IS NULL OR \"BullishConfidence\" BETWEEN 0 AND 100) AND (\"BearishConfidence\" IS NULL OR \"BearishConfidence\" BETWEEN 0 AND 100) AND \"DataQuality\" BETWEEN 0 AND 100 AND \"ContextCoverage\" BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_M3_score_state", "(\"State\" IN ('complete','partial') AND \"Composite\" IS NOT NULL AND \"BullishConfidence\" IS NOT NULL AND \"BearishConfidence\" IS NOT NULL AND \"DataQuality\" >= 50) OR (\"State\" = 'not-ready' AND \"Composite\" IS NULL AND \"BullishConfidence\" IS NULL AND \"BearishConfidence\" IS NULL)");
                        });
                });

            modelBuilder.Entity("Analysis.Infrastructure.Persistence.ScoringBatchRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("AsOfUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatingTransactionId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValueSql("pg_current_xact_id()::text");

                    b.Property<string>("InputHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("KnowledgeCutoffUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RecordKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UniverseJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ModelId", "AsOfUtc")
                        .IsUnique();

                    b.ToTable("ScoringBatches", "research", t =>
                        {
                            t.HasCheckConstraint("CK_M3_batch_clock", "\"KnowledgeCutoffUtc\" >= \"AsOfUtc\" AND \"CreatedAtUtc\" >= \"KnowledgeCutoffUtc\" AND EXTRACT(EPOCH FROM \"AsOfUtc\") % 3600 = 0");

                            t.HasCheckConstraint("CK_M3_record_kind", "\"RecordKind\" = 'research-reconstruction'");
                        });
                });

            modelBuilder.Entity("Analysis.Infrastructure.Persistence.ScoringModelRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ManifestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ManifestJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("ScoringModels", "research");
                });

            modelBuilder.Entity("Analysis.Domain.InstrumentRef", b =>
                {
                    b.HasOne("Analysis.Domain.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Analysis.Infrastructure.Persistence.ProviderRow", null)
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Analysis.Infrastructure.Persistence.CategoryScoreRow", b =>
                {
                    b.HasOne("Analysis.Infrastructure.Persistence.ScoreSnapshotRow", null)
                        .WithMany()
                        .HasForeignKey("ScoreId", "BatchId")
                        .HasPrincipalKey("Id", "BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Analysis.Infrastructure.Persistence.FeatureSnapshotRow", b =>
                {
                    b.HasOne("Analysis.Domain.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Analysis.Infrastructure.Persistence.ScoringBatchRow", null)
                        .WithMany()
                        .HasForeignKey("BatchId", "AsOfUtc", "ModelId")
                        .HasPrincipalKey("Id", "AsOfUtc", "ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Analysis.Infrastructure.Persistence.FeatureValueRow", b =>
                {
                    b.HasOne("Analysis.Infrastructure.Persistence.FeatureSnapshotRow", null)
                        .WithMany()
                        .HasForeignKey("SnapshotId", "BatchId")
                        .HasPrincipalKey("Id", "BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Analysis.Infrastructure.Persistence.InputConflictRow", b =>
                {
                    b.HasOne("Analysis.Infrastructure.Persistence.ScoringBatchRow", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Analysis.Infrastructure.Persistence.QuarantineRow", null)
                        .WithMany()
                        .HasForeignKey("ConflictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Analysis.Infrastructure.Persistence.InputObservationRow", b =>
                {
                    b.HasOne("Analysis.Infrastructure.Persistence.ScoringBatchRow", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Analysis.Infrastructure.Persistence.ObservationRow", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId", "Kind", "EventTimeUtc", "PeriodSeconds")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Analysis.Infrastructure.Persistence.ObservationRow", b =>
                {
                    b.HasOne("Analysis.Domain.InstrumentRef", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Analysis.Infrastructure.Persistence.PayloadRow", null)
                        .WithMany()
                        .HasForeignKey("PayloadId", "InstrumentId")
                        .HasPrincipalKey("Id", "InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Analysis.Infrastructure.Persistence.PayloadRow", b =>
                {
                    b.HasOne("Analysis.Domain.InstrumentRef", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Analysis.Infrastructure.Persistence.QuarantineRow", b =>
                {
                    b.HasOne("Analysis.Domain.InstrumentRef", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Analysis.Infrastructure.Persistence.ScoreSnapshotRow", b =>
                {
                    b.HasOne("Analysis.Infrastructure.Persistence.FeatureSnapshotRow", null)
                        .WithOne()
                        .HasForeignKey("Analysis.Infrastructure.Persistence.ScoreSnapshotRow", "SnapshotId", "BatchId", "AssetId", "AsOfUtc", "ModelId")
                        .HasPrincipalKey("Analysis.Infrastructure.Persistence.FeatureSnapshotRow", "Id", "BatchId", "AssetId", "AsOfUtc", "ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Analysis.Infrastructure.Persistence.ScoringBatchRow", b =>
                {
                    b.HasOne("Analysis.Infrastructure.Persistence.ScoringModelRow", null)
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
