import { test, expect, ready } from '../support/rankings'

test('workspace navigation and history preserve the successful comparison cache', async ({ page, api }) => {
  await page.goto('/'); await ready(page)
  await expect(page.getByRole('button', { name: /devtools|inspector/i })).toHaveCount(0)
  expect(await page.evaluate(() => performance.getEntriesByType('resource').map(resource => resource.name)))
    .not.toEqual(expect.arrayContaining([expect.stringMatching(/devtools|development-tools|vitest|playwright|axe/)]))
  await page.getByRole('navigation').getByRole('link', { name: 'About', exact: true }).click()
  await expect(page).toHaveURL('/about')
  await expect(page.getByRole('heading', { name: 'An inspectable research process.' })).toBeVisible()
  await page.goBack(); await ready(page)
  await page.goForward(); await expect(page).toHaveURL('/about')
  await page.getByRole('navigation').getByRole('link', { name: 'Workspace', exact: true }).click(); await ready(page)
  expect(api.requests).toHaveLength(1)
})
test('about loads directly and survives reload without a rankings request', async ({ page, api }) => {
  await page.goto('/about')
  await expect(page.getByText(/Exchange trading and asset custody are outside its scope/)).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'An inspectable research process.' })).toBeVisible()
  expect(api.requests).toHaveLength(0)
})
test('missing page returns to the ranking workspace', async ({ page }) => {
  await page.goto('/missing-page')
  await expect(page.getByRole('heading', { name: 'Page not found' })).toBeVisible()
  await page.getByRole('link', { name: 'Return to workspace' }).click(); await ready(page)
})
test('keyboard users can skip navigation and the page fits the viewport', async ({ page }) => {
  await page.goto('/'); await ready(page)
  await page.keyboard.press('Tab')
  await expect(page.getByRole('link', { name: 'Skip to content' })).toBeFocused()
  await expect(page.getByRole('link', { name: 'Skip to content' })).toBeInViewport()
  await page.keyboard.press('Enter'); await expect(page.getByRole('main')).toBeFocused()
  await page.keyboard.press('Tab'); await expect(page.getByRole('textbox', { name: 'Model ID' })).toBeFocused()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})
