<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../Analysis.Application/Analysis.Application.csproj" />
    <PackageReference Include="Npgsql" Version="[10.0.3]" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="[10.0.3]" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="[10.0.11]" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="[10.0.11]" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="[10.0.11]" PrivateAssets="all" />
    <PackageReference Include="StackExchange.Redis" Version="[3.1.31]" />
  </ItemGroup>
</Project>
