<Project Sdk="MSTest.Sdk/4.3.3">
  <PropertyGroup>
    <RootNamespace>Analysis.Worker.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Analysis.Worker/Analysis.Worker.csproj" />
  </ItemGroup>
</Project>
